In [148]:
import pandas as pd
from collections import Counter

all_matches = pd.read_csv('2015_2019_All_Match_Results.csv', encoding  = 'cp949')
all_matches

club_tourney = []
#동호인 제외
for i in range(len(all_matches)):
    if '동호인' in all_matches['Tournament'][i]:
        club_tourney.append(i)
    
    
#선수권 대회
pro_matches = all_matches.drop(club_tourney, axis = 0)
match_count = Counter(pro_matches['Player']).most_common()

#승리한 경기
won_matches = pro_matches[pro_matches['Result'] == '승'].reset_index(drop=True)

#남자부 경기
won_matches_m = won_matches[won_matches['Gender'] == '남'].reset_index(drop=True)
count = Counter(won_matches_m['Player']).most_common()


#남자부 선수
players_m = pro_matches['Player'][pro_matches['Gender'] == '남'].drop_duplicates().sort_values().reset_index(drop =True)

players_m

0      Afy Luqman Bin Noor Afendy
1           Benedict Chan Jia Wei
2               DUFFY CARL JOSEPH
3                 DUFFYCARLJOSEPH
4                     LEUNG Henry
                  ...
295                           황영덕
296                           황영웅
297                           황중원
298                           황중찬
299                           황지훈
Name: Player, Length: 300, dtype: object

In [149]:
match_dic={}

for data in match_count:
    match_dic[data[0]] = data[1]

In [150]:
win_dic = {}

for data in count:
    win_dic[data[0]] = data[1]

In [151]:
per_dic = {}

for key in win_dic:
    results = []
    
    won = win_dic[key]
    results.append(won)
    matches = match_dic[key]
    results.append(matches)
    percent = round(float(won)/float(matches)*100, 2)
    results.append(percent)
    
    per_dic[key] = results

In [315]:
result_df = pd.DataFrame().from_dict(per_dic, orient='index')
result_df.columns = ['Won', 'Matches', "Win_%"]
result_df['Starting Elo'] = 0
#result_df['Weighted Starting El']
result_df['Category'] = '일반부'
result_df.sort_values('Win_%', ascending = False)


for i in range(len(result_df)):
    win_per = result_df['Win_%']
    if win_per[i] > 80:
        result_df['Starting Elo'][i] = 1800
    elif 80 >= win_per[i] > 70:    
        result_df['Starting Elo'][i] = 1600
    elif 70 >= win_per[i] > 60:
        result_df['Starting Elo'][i] = 1400
    elif 60 >= win_per[i] > 50:
        result_df['Starting Elo'][i] = 1200
    else:
        result_df['Starting Elo'][i] = 1000

result_df = result_df.reset_index()
result_df

<ipython-input-315-5b9c93447912>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['Starting Elo'][i] = 1800
<ipython-input-315-5b9c93447912>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['Starting Elo'][i] = 1600
<ipython-input-315-5b9c93447912>:16: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['Starting Elo'][i] = 1400
<ipython-input-315-5b9c93447912>:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['Starting Elo'][i] = 1200
<ipython-input-315-5b9c93447912>:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df['Starting Elo'][i] = 1000

    index  Won  Matches  Win_%  Starting Elo Category
0     이민우   62       68  91.18          1800      일반부
1     고영조   54       62  87.10          1800      일반부
2     박성찬   46       64  71.88          1600      일반부
3     이인우   45       62  72.58          1600      일반부
4     유재진   42       50  84.00          1800      일반부
..    ...  ...      ...    ...           ...      ...
193   김태년    1        8  12.50          1000      일반부
194   김경진    1        4  25.00          1000      일반부
195   박경민    1        6  16.67          1000      일반부
196   최성은    1        4  25.00          1000      일반부
197   김태규    1        5  20.00          1000      일반부

[198 rows x 6 columns]

In [316]:
index = result_df.index
result_19 = pro_matches[pro_matches['Year'] == 2019]
result_18 = pro_matches[pro_matches['Year'] == 2018]

for i in range(len(result_df)):
    try:
        player = result_df['index'].iloc[i]
        category = result_19[result_19['Player'] == player]['Category'].reset_index(drop=True)
        #print(category)
        #print(player['Player'][0], category[0])
        #print(category.iloc[0], i)
        #print(player)
        #print(category.iloc[0])
        
        if str(category.iloc[3]) == '대학부':
            #print(category.iloc[0])
            result_df['Category'].iloc[i]='대학부'
            result_df['Starting Elo'].iloc[i] = result_df['Starting Elo'].iloc[i]*0.8
        
        elif str(category.iloc[3]) == '고등부':
            result_df['Category'].iloc[i]='고등부'
            result_df['Starting Elo'].iloc[i] = result_df['Starting Elo'].iloc[i]*0.7
        
        elif str(category.iloc[3]) == '중등부':
            result_df['Category'].iloc[i]='중등부'
            result_df['Starting Elo'].iloc[i] = result_df['Starting Elo'].iloc[i]*0.5
        
        elif str(category.iloc[3]) == '초등부':
            result_df['Category'].iloc[i]='초등부'
            result_df['Starting Elo'].iloc[i] = result_df['Starting Elo'].iloc[i]*0.3
            #print(category[0])
    except IndexError:
        pass
result_df

C:\Users\h00ns\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

    index  Won  Matches  Win_%  Starting Elo Category
0     이민우   62       68  91.18        1260.0      고등부
1     고영조   54       62  87.10        1800.0      일반부
2     박성찬   46       64  71.88        1280.0      대학부
3     이인우   45       62  72.58        1600.0      일반부
4     유재진   42       50  84.00        1800.0      일반부
..    ...  ...      ...    ...           ...      ...
193   김태년    1        8  12.50        1000.0      일반부
194   김경진    1        4  25.00        1000.0      일반부
195   박경민    1        6  16.67        1000.0      일반부
196   최성은    1        4  25.00        1000.0      일반부
197   김태규    1        5  20.00        1000.0      일반부

[198 rows x 6 columns]

In [319]:
['Category'] = '대학부'

<ipython-input-319-29702d743709>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df[result_df['index'] == '이상훈']['Category'] = '대학부'

In [354]:
result_df[result_df['index'] == '이상훈']['Starting Elo'] = result_df[result_df['index'] == '이상훈']['Starting Elo']*0.8
result_df[result_df['index'] == '이상훈'].loc['Category'] = '대학부'
result_df[result_df['index'] == '조단우']

<ipython-input-354-aac7c05e07d5>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  result_df[result_df['index'] == '이상훈']['Starting Elo'] = result_df[result_df['index'] == '이상훈']['Starting Elo']*0.8
C:\Users\h00ns\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)

    index  Won  Matches  Win_%  Starting Elo Category
150   조단우    2        2  100.0        1800.0      일반부

In [342]:
result_df['Category'].iloc[47] = '대학부'
result_df['Starting Elo'].iloc[47] = 1200*0.8

In [344]:
result_df

    index  Won  Matches  Win_%  Starting Elo Category
0     이민우   62       68  91.18        1260.0      고등부
1     고영조   54       62  87.10        1800.0      일반부
2     박성찬   46       64  71.88        1280.0      대학부
3     이인우   45       62  72.58        1600.0      일반부
4     유재진   42       50  84.00        1800.0      일반부
..    ...  ...      ...    ...           ...      ...
193   김태년    1        8  12.50        1000.0      일반부
194   김경진    1        4  25.00        1000.0      일반부
195   박경민    1        6  16.67        1000.0      일반부
196   최성은    1        4  25.00        1000.0      일반부
197   김태규    1        5  20.00        1000.0      일반부

[198 rows x 6 columns]

# Add Players

In [153]:
#won_matches_m = won_matches_m[won_matches_m['Category'] == '일반부'].reset_index(drop=True)
won_matches_m['Player'] = won_matches_m['Player'].replace('유승룡', '유승용')
players_1 = won_matches_m['Player']
players_2 = won_matches_m['Oppoenent']
players_m = players_1.append(players_2).drop_duplicates().reset_index(drop =True)

In [155]:
from elopy import *
from tqdm import tqdm

M = Implementation()

for player in players_m:
    M.addPlayer(str(player))

rating_list = M.getRatingList()
len(rating_list)

300

In [32]:
count = 0
ls = []

for idx in tqdm(range(len(won_matches_m))):
    try:
        Winner = str(won_matches_m['Player'][idx])
        Loser = str(won_matches_m['Oppoenent'][idx])
        M.recordMatch(Winner,Loser,winner=Winner)
    
    except:
        count+=1
        ls.append(idx)
        print(idx, Winner, Loser)
        pass


male_rating = M.getRatingList()
print(count)

100%|██████████| 483/483 [00:00<00:00, 40283.33it/s]

0

In [ ]:
miss = won_matches_m.iloc[ls]['Player'].to_list()
miss_o = won_matches_m.iloc[ls]['Oppoenent'].to_list()

miss.extend(miss_o)
len(miss)
miss

In [156]:
res = []
for i in miss:
    if i not in res:
        res.append(i)

In [40]:
R_A = 1500
R_B = 1200

E_A = (1/(1+10**((R_B-R_A)/400)))
E_B = (1/(1+10**((R_A-R_B)/400)))

K=30

In [41]:
S_A = 1
S_B = 1

In [43]:
R_A_1 = R_A + K*(S_A-E_A)
R_A_1

1504.5293867163398

In [ ]:

rating_list
for data in rating_list:
    try:
        if result_df[result_df['index'] == data[0]]['Matches'].iloc[0] > 10:
            elo_dic[data[0]] = result_df.loc[data[0]]['Starting Elo']
    except KeyError:
        print(data[0])
        pass
elo_dic

In [373]:
elo_dic={}

for i in range(len(result_df)):
    if result_df['Matches'].iloc[i]>10:
        elo_dic[result_df['index'].iloc[i]] = result_df['Starting Elo'].iloc[i]

elo_dic

{'이민우': 1260.0,
 '고영조': 1800.0,
 '박성찬': 1280.0,
 '이인우': 1600.0,
 '유재진': 1800.0,
 '이건동': 1600.0,
 '박종명': 1600.0,
 '탁효진': 1280.0,
 '강현범': 1120.0,
 '박승민': 979.9999999999999,
 '이승택': 1600.0,
 '이세현': 1600.0,
 '유덕재': 1280.0,
 '김석진': 1600.0,
 '강우석': 979.9999999999999,
 '김건': 900.0,
 '김현동': 1400.0,
 '이승준': 1800.0,
 '류한동': 1600.0,
 '정대훈': 1200.0,
 '유정민': 840.0,
 '이년호': 1400.0,
 '황중원': 1400.0,
 '우창욱': 1200.0,
 '김정원': 960.0,
 '김성영': 1200.0,
 '이동준': 1200.0,
 '진승우': 1400.0,
 '문석호': 960.0,
 '한승철': 1400.0,
 '구성진': 960.0,
 '이동민': 1400.0,
 '오민재': 1200.0,
 '오서진': 800.0,
 '오성학': 1400.0,
 '김지환': 840.0,
 '유성연': 1400.0,
 '최호진': 979.9999999999999,
 '김승현': 840.0,
 '유승용': 1400.0,
 '김남경': 1400.0,
 '탁형진': 960.0,
 '이라온': 840.0,
 '임재현': 1000.0,
 '이시형': 1200.0,
 '최동진': 1200.0,
 '나주영': 600.0,
 '이상훈': 960.0,
 '조영훈': 1000.0,
 '신헌수': 1000.0,
 '이용정': 1000.0,
 '유용민': 1000.0,
 '한종수': 700.0,
 '강유상': 1000.0,
 '권현준': 1400.0,
 '김동우': 1200.0,
 '황중찬': 1000.0,
 '김태현': 800.0,
 '이종혁': 540.0,
 '오수현': 1200.0,
 '유호제': 1200.0,
 '배연우': 1200.0,
 '신승용': 1000.0,
 '최원석': 1200.0,
 '유정욱': 500.0,
 '유승한': 1000.0,
 '김성집': 1000.0,
 '백승엽': 1000.0,
 '이현욱': 1000.0,
 '이승호': 1000.0,
 '김사무엘': 700.0,
 '김광원': 1000.0,
 '이지석': 700.0,
 '임주안': 420.0,
 '최규희': 1000.0,
 '김진성': 1000.0,
 '김예일': 1200.0,
 '지동현': 700.0,
 '서무진': 700.0,
 '양재혁': 1000.0,
 '백승재': 1000.0,
 '이원기': 1000.0,
 '류승한': 1400.0,
 '이강인': 500.0,
 '박정식': 800.0,
 '최상철': 1000.0,
 '한승호': 800.0,
 '황수연': 1000.0,
 '박준형': 1000.0,
 '이상지': 1000.0,
 '박준현': 1000.0,
 '심규영': 800.0,
 '한성수': 1000.0,
 '정태경': 500.0,
 '이동규': 700.0,
 '이승렬': 1000.0,
 '정민채': 1000.0,
 '김재완': 1000.0,
 '이민규': 700.0,
 '최현우': 700.0,
 '김병관': 500.0,
 '박시형': 700.0,
 '김현인': 800.0,
 '조용직': 1000.0,
 '박한솔': 1000.0,
 '김대운': 1000.0,
 '박준하': 1000.0,
 '문병준': 1000.0,
 '이시훈': 1000.0,
 '임지훈': 1000.0,
 '이현준': 1000.0}

In [374]:
def expected_result(elo_a, elo_b):
    """
    https://en.wikipedia.org/wiki/Elo_rating_system#Mathematical_details
    """
    expect_a = 1.0/(1+10**((elo_b - elo_a)/elo_width))
    return expect_a

In [375]:
def update_elo(winner_elo, loser_elo):
    """
    https://en.wikipedia.org/wiki/Elo_rating_system#Mathematical_details
    """
    expected_win = expected_result(winner_elo, loser_elo)
    change_in_elo = k_factor * (1-expected_win)
    winner_elo += change_in_elo
    loser_elo -= change_in_elo
    return winner_elo, loser_elo

In [376]:
elo_width = 400
k_factor = 20

for i in range(len(won_matches_m)):
    try:
        winner = won_matches_m['Player'].iloc[i]
        loser = won_matches_m['Oppoenent'].iloc[i]

        winner_elo = elo_dic[str(winner)]
        loser_elo = elo_dic[str(loser)]

        elo_dic[str(winner)], elo_dic[str(loser)] = update_elo(winner_elo, loser_elo)
    except KeyError:
        pass

In [377]:
elo_dic = dict(sorted(elo_dic.items(), key=lambda item: item[1], reverse = True))

In [407]:
ranking_df = pd.DataFrame.from_dict(elo_dic, orient = 'index')
ranking_df = ranking_df.reset_index()

ranking_df = ranking_df.rename(columns = {'index':'Name', 0: 'Rating'} )

In [411]:
ranking_df.to_excel('preliminary_ranking.xlsx', index =False)